import { Header } from "@/common/components/header/Header";
import { MuiProvider } from "@/common/components/theme-provider/ThemeProvider";
import { ReduxProvider } from "@/common/components/redux-provider/ReduxProvider";
import { FC, ReactNode } from "react";
import { Source_Sans_Pro } from "next/font/google";
import "./globals.css";

const sourceSansPro = Source_Sans_Pro({
  weight: ["400", "700"],
  subsets: ["latin"]
});

export const metadata = {
  title: "The Many Saints",
  description: "Generated by create next app"
};

interface Props {
  children: ReactNode;
}

const RootLayout: FC<Props> = ({ children }) => {
  return (
    <html lang="en">
      <body className={sourceSansPro.className}>
        <ReduxProvider>
          <MuiProvider>
            <Header />
            {children}
          </MuiProvider>
        </ReduxProvider>
      </body>
    </html>
  );
};

export default RootLayout;
